removed broken check for services

diff --git a/dockerwifi b/dockerwifi
--- a/dockerwifi
+++ b/dockerwifi
@@ -14,6 +14,8 @@ ARCH=$(uname -m)
 DOCKER_IMAGE=dockerwifi
 DOCKER_BUILDFILE=build/Dockerfile
 SSID=dockerwifi # default
+PASSPHRASE=password123
+CHANNEL=1 # default
 AP_ADDR=192.168.254.1
 SUBNET=192.168.254.0
 clear
@@ -33,66 +35,7 @@ EOF
 # Check for problematic services
 # Borrowed and modified from #aircrack
 function checkservices() {
-
-  #this test means it errored and said it was busybox since busybox doesn't print without error
-  if (ps -A 2>&1 | grep -q BusyBox)
-  then
-    #busybox in openwrt cannot handle -A but its output by default is -A
-    psopts=""
-  else
-    psopts="-A"
-  fi
-  if ( ps -o comm= 2>&1 | grep -q BusyBox )
-  then
-    #busybox in openwrt cannot handle -o
-    pso="0"
-  else
-    pso="1"
-  fi
-
-  PROCESSES="wpa_action\|wpa_supplicant\|wpa_cli\|dhclient\|ifplugd\|dhcdbd\|dhcpcd\|udhcpc\|NetworkManager\|knetworkmanager\|avahi-autoipd\|avahi-daemon\|wlassistant\|wifibox\|net_applet\|wicd-daemon\|wicd-client\|iwd"
-
-  if [ -x "$(command -v service 2>&1)" ]; then
-    service network-manager stop 2> /dev/null > /dev/null
-    service NetworkManager stop 2> /dev/null > /dev/null
-    service avahi-daemon stop 2> /dev/null > /dev/null
-    while [ $? -eq 1 ]; do
-      # Sometimes avahi is persistent and keeps being restarted by systemd.
-      # It's usually 4 times that it needs to be stopped
-      service avahi-daemon stop 2> /dev/null > /dev/null
-    done
-    service wicd stop 2> /dev/null > /dev/null
-  fi
-
-  unset match
-  if [ "${pso}" = 1 ]; then
-    match="$(ps ${psopts} -o comm= | grep ${PROCESSES} | grep -v grep | wc -l)"
-  elif [ "${pso}" = 0 ]; then
-    #openwrt busybox grep hits on itself so we -v it out
-    match="$(ps ${psopts} | grep ${PROCESSES} | grep -v grep | wc -l)"
-  fi
-  if [ ${match} -gt 0 ]; then
-    printf "[INFO] Found $match processes that could cause trouble.\n"
-  else
-    printf "No interfering processes found\n"
-  fi
-  if [ ${match} -gt 0 ]; then
-    if [ "${pso}" = "1" ]; then
-      ps ${psopts} -o pid=PID -o comm=Name | grep "${PROCESSES}\|PID"
-    else
-      ps ${psopts} | grep "${PROCESSES}\|PID | grep -v grep"
-    fi
-    #we have to use signal 9 because things like nm actually respawn wpa_supplicant too quickly
-    if [ "${pso}" = "1" ]; then
-      for pid in $(ps ${psopts} -o pid= -o comm= | grep ${PROCESSES} | awk '{print $1}'); do
-        kill -9 ${pid}
-      done
-    else
-      for pid in $(ps ${psopts} | grep ${PROCESSES} | grep -v grep | awk '{print $1}'); do
-        kill -9 ${pid}
-      done
-    fi
-  fi
+  systemctl stop network-manager
 }
 
 if [ "$EUID" -ne 0 ]; then
@@ -110,7 +53,9 @@ while test $# -gt 0; do
       echo " "
       echo "Argumentss:"
       echo "-h, --help          show brief help"
-      echo "-i, --interface     specify and interface (required)"
+      echo "-i, --interface     specify an interface (required)"
+      echo "-c, --channel       channel number"
+      echo "--passphrase        passphrase for WPA-PSK APs"
       echo "--ssid              specify an SSID"
       echo "--version           print version"
       exit 0
@@ -125,12 +70,32 @@ while test $# -gt 0; do
       fi
       shift
       ;;
+    -c|--channel)
+      shift
+      if test $# -gt 0; then
+        export CHANNEL=$1
+      else
+        echo "Channel number required. Exiting..."
+        exit 1
+      fi
+      shift
+      ;;
     --ssid)
       shift
       if test $# -gt 0; then
         export SSID=$1
       else
         echo "SSID argument used but no same was provided. Exiting..."
+        exit 1
+      fi
+      shift
+      ;;
+    --passphrase)
+      shift
+      if test $# -gt 0; then
+        export PASSPHRASE=$1
+      else
+        echo "Passphrase argument was used but no passphrase was provided. Exiting..."
         exit 1
       fi
       shift
@@ -156,9 +121,6 @@ fi
 
 PHY=$(cat /sys/class/net/$IFACE/phy80211/name)
 
-
-# TODO: Check architecture, use custom dockerfile
-
 # Check that docker is installed and running
 $(docker info > /dev/null 2>&1)
 if [[ $? -ne 0 ]]; then
@@ -166,7 +128,7 @@ if [[ $? -ne 0 ]]; then
   exit 1
 fi
 
-echo -e "[+] Docker Service found!"
+echo -e "[+] Checking Docker Service:\t\t${GREEN}Success${NC}"
 
 if ! [ -e /sys/class/net/$IFACE ]; then
   echo -e "${RED}[ERROR]${NC} The specified interface does not exist. Exiting..."
@@ -179,36 +141,32 @@ if [[ $? -eq 1 ]]; then
   exit 1
 fi
 
-echo -e "[+] Interface ${GREEN}$IFACE${NC} supports ${GREEN}AP${NC} mode"
+echo -e "[+] Checking support for AP Mode:\t${GREEN}Success${NC}"
 CHANNELS=$(iw phy $PHY info | sed -n '/Frequencies/,/^\s*Supported commands:\s*$/{//!p}' | grep -vE "disabled|IR" | grep -oP '\[\K[^]]+' | awk 'BEGIN {ORS=" "} {print}')
-echo -e "[+] Interface supports channels ${GREEN}$CHANNELS${NC}"
+echo -e "[+] Supported Channels: ${GREEN}$CHANNELS${NC}"
 
 # Get current status of card
 MODE=$(iw dev | grep -A5 $IFACE | grep type | cut -d" " -f2)
 if [[ $MODE == "monitor" ]]; then
-  echo -e "${BLUE}[INFO]${NC} Radio mode is set to ${RED}Monitor${NC} mode"
+  echo -e "${BLUE}[INFO]${NC} Radio mode: ${RED}Monitor${NC}"
+  echo -e "${MAGENTA}[!]${NC} Radio will be set tp ${GREEN}AP${NC}"
 elif [[ $MODE == "managed" ]]; then
-  echo -e "${BLUE}[INFO]${NC} Radio mode is set to ${RED}Managed${NC} mode"
+  echo -e "${BLUE}[INFO]${NC} Radio mode: ${RED}Managed${NC}"
+  echo -e "${MAGENTA}[!]${NC} Radio will be set to ${GREEN}AP${NC}"
 elif [[ $MODE == "AP" ]]; then
-  echo -e "[+] Radio mode is set to ${GREEN}AP${NC}"
+  echo -e "[+] Radio mode: ${GREEN}AP${NC}"
 else
-  echo -e "${RED}[ERROR]${NC} Unknown interface mode. Exiting..."
+  echo -e "${RED}[ERROR]${NC} Unknown Radio state: ${RED}$MODE${NC}. Exiting..."
   exit 1
 fi
 
 # Check for route conflict 
 if [[ $(ip r | grep default | cut -d " " -f5) == "$IFACE" ]]; then
-  echo -e "${BLUE}[INFO]${NC} $IFACE configured as your default route.\nInternet connectivity may be impacted while dockerWIFI is running"
-  while true; do
-    read -p "Do you want to continue? [y/n]: " prompt
-      case $prompt in 
-        [Yy]* ) 
-          break;;
-        [Nn]* ) exit;;
-        * ) echo "Please enter y/n";;
-      esac
-  done
+  echo -e "${BLUE}[INFO]]${NC} $IFACE configured as your default route."
 fi
+
+echo -e "[+] Bringing down network management services..."
+checkservices
 
 echo -e "[+] Building the docker image ${GREEN}$DOCKER_IMAGE${NC}..."
 docker build -q --rm -t $DOCKER_IMAGE -f $DOCKER_BUILDFILE . > /dev/null
@@ -219,22 +177,8 @@ fi
 echo -e "[+] Successfully built docker image: ${GREEN}$DOCKER_IMAGE${NC}"
 
 
-# Check for problematic services
-while true; do
-  echo -e "${BLUE}[INFO]${NC} Network services may impact dockerwifi's ability to control radio interfaces"
-  read -p "Should we identify and kill problematic services first? [y/n]: " chk
-  case $chk in
-    [Yy]* )
-      checkservices
-      break
-      ;;
-    [Nn]* )
-      break
-      ;;
-    * ) echo "Please enter y/n";;
-  esac
-done
-
 DOCKER_NAME="dockerwifi_$IFACE"
 echo -e "${MAGENTA}[!] Executing container: ${DOCKER_NAME}...${NC}"
-docker run -it --rm --name $DOCKER_NAME -e "TERM=xterm-256color" -e SSID=${SSID} -e AP_ADDR=${AP_ADDR} -e IFACE=${IFACE} -e SUBNET=${SUBNET} --net host --privileged $DOCKER_IMAGE
+docker run -it --rm --name $DOCKER_NAME -e "TERM=xterm-256color" -e SSID=${SSID} -e PASSPHRASE=${PASSPHRASE} -e CHANNEL=${CHANNEL} -e AP_ADDR=${AP_ADDR} -e IFACE=${IFACE} -e SUBNET=${SUBNET} --net host --privileged $DOCKER_IMAGE
+echo -e "[+] Bringing up network managment services..."
+systemctl restart network-manager
